export default {
  fontFamily: "'Chinese Quote',-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Hiragino Sans GB','Microsoft YaHei','Helvetica Neue',Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'",
  colors: {
    main: '#4a4a4a',
    white: '#ffffff',
    secondary: '#9b9b9b',
    lightGray: '#f8f9fa',
    primary: '#1890ff',
    darkPrimary: '#096dd9',
    lightPrimary: '#91d5ff',
    lighterPrimary: '#e6f7ff',
    border: '#e3e3e3',
    success: '#66bb6a',
    darkSuccess: '#237804',
    danger: '#ff4d4f',
    darkDanger: '#c61322',
    lightDanger: '#fcd1d5',
    warning: '#ffc53d',
    darkWarning: '#ddb800',
    lightWarning: '#fff7cd',
    mainBackground: '#f5f5f5',
    darkerBackground: '#fff',
    gray: '#595959',
    info: '#17a2b8',
    black: '#343a40',
    darkGray: '#212529',
  },
  borderRadius: '6px',
  borderCircle: '100vw',
  borderSmall: '3px',
  gridGap: 15,
  tablePadding: 8,
};
