FROM node:6.9.2
RUN npm i -g yarn

VOLUME ["~/.docker-yarn-cache", "/root/yarn-cache"]

WORKDIR /app
CMD sh -c "echo \"Start\" && \
  NODE_ENV=development yarn install && \
  NODE_ENV=production yarn run build && \
  cd build && NODE_ENV=production yarn install"