import { Err } from '@lskjs/err';
import { log } from '@lskjs/log/log';
import { getComment, jsonToFile } from '@lskjs/stringify';
import { mapSeries } from 'fishbird';
import fs from 'fs/promises';

import { GithubService } from '../services/GithubService';
import { GitlabService } from '../services/GitlabService';
import { Service } from '../services/Service';
import { getFiles } from '../utils/getFiles';

export async function buildCommand(serviceDirname, options: any = {}) {
  const buildDirDir = options.buildDir || `${serviceDirname}/build`;

  // eslint-disable-next-line import/no-dynamic-require
  const config = require(`${serviceDirname}/config.js`);

  await fs.unlink(`${buildDirDir}`).catch(() => {});
  await fs.mkdir(buildDirDir, { recursive: true });

  const serviceName = config.service?.serviceName;
  if (!serviceName) throw new Err('!serviceName');

  let service: Service;
  if (serviceName === 'github') {
    service = new GithubService({
      ...config.service,
      ...options,
    });
  } else if (serviceName === 'gitlab') {
    service = new GitlabService({
      ...config.service,
      ...options,
    });
  } else {
    throw new Err('incorrect serviceName', { serviceName });
  }

  const { files = [] } = config;
  await mapSeries(files, async (fileOptions: any) => {
    const { type, filename, handler } = fileOptions;
    const res = await handler(fileOptions, config);
    const comment = getComment({
      filename,
      values: [
        ['Server', service.getServiceLink()],
        ['Project', service.getProjectPath()],
        ['Project ID', service.getProjectId()],
        ['Project Url', service.getProjectUrl()],
        ['CI/CD Setting', service.getProjectCICDSettingURL()],
      ],
      footer:
        service.getProjectCredsUrl() &&
        `
Auto generated by ${service.getProjectCredsUrl()}
If you want to change something, please contact admin repo.
      `.trim(),
    });
    await jsonToFile(`${buildDirDir}/${filename}`, res, {
      type,
      compare: !options.force,
      comment,
    });
  });
}
export async function buildDeepCommand(dirname, options = {}) {
  const files = await getFiles(dirname);
  return mapSeries(files, async ({ filename, dir }) => {
    await buildCommand(dir, options).catch((err) => {
      log.error(`Build error ${filename}: `, err);
    });
  });
}
