export default {  
  'src/A/A.story.jsx': require('../src/A/A.story.jsx'),
  'src/Avatar/Avatar.story.jsx': require('../src/Avatar/Avatar.story.jsx'),
  'src/AvatarGroup/AvatarGroup.story.jsx': require('../src/AvatarGroup/AvatarGroup.story.jsx'),
  'src/Button/Button.story.jsx': require('../src/Button/Button.story.jsx'),
  'src/Card/Card.story.jsx': require('../src/Card/Card.story.jsx'),
  'src/Form/Form.story.jsx': require('../src/Form/Form.story.jsx'),
  'src/Modal/Modal.story.jsx': require('../src/Modal/Modal.story.jsx'),
  'src/Page/Page.story.jsx': require('../src/Page/Page.story.jsx'),
  'src/Slide/Slide.story.jsx': require('../src/Slide/Slide.story.jsx'),
  'src/StatefulButton/StatefulButton.story.jsx': require('../src/StatefulButton/StatefulButton.story.jsx'),
  'src/StatusButton/StatusButton.story.jsx': require('../src/StatusButton/StatusButton.story.jsx'),
  'src/Test.story.jsx': require('../src/Test.story.jsx'),
  'src/UrlButton/UrlButton.story.jsx': require('../src/UrlButton/UrlButton.story.jsx'),
};